// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	base "github.com/awfm/consensus/model/base"

	mock "github.com/stretchr/testify/mock"
)

// Builder is an autogenerated mock type for the Builder type
type Builder struct {
	mock.Mock
}

// Arc provides a mock function with given fields:
func (_m *Builder) Arc() (base.Hash, error) {
	ret := _m.Called()

	var r0 base.Hash
	if rf, ok := ret.Get(0).(func() base.Hash); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(base.Hash)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
