// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/alvalor/consensus/model"
	mock "github.com/stretchr/testify/mock"
)

// Graph is an autogenerated mock type for the Graph type
type Graph struct {
	mock.Mock
}

// Confirm provides a mock function with given fields: vertexID
func (_m *Graph) Confirm(vertexID model.Hash) error {
	ret := _m.Called(vertexID)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Hash) error); ok {
		r0 = rf(vertexID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Extend provides a mock function with given fields: vertex
func (_m *Graph) Extend(vertex *model.Vertex) error {
	ret := _m.Called(vertex)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Vertex) error); ok {
		r0 = rf(vertex)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Final provides a mock function with given fields:
func (_m *Graph) Final() (*model.Vertex, bool) {
	ret := _m.Called()

	var r0 *model.Vertex
	if rf, ok := ret.Get(0).(func() *model.Vertex); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Vertex)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}
