// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import base "github.com/alvalor/consensus/model/base"

import message "github.com/alvalor/consensus/model/message"
import mock "github.com/stretchr/testify/mock"

// Network is an autogenerated mock type for the Network type
type Network struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: proposal
func (_m *Network) Broadcast(proposal *message.Proposal) error {
	ret := _m.Called(proposal)

	var r0 error
	if rf, ok := ret.Get(0).(func(*message.Proposal) error); ok {
		r0 = rf(proposal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transmit provides a mock function with given fields: vote, recipientID
func (_m *Network) Transmit(vote *message.Vote, recipientID base.Hash) error {
	ret := _m.Called(vote, recipientID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*message.Vote, base.Hash) error); ok {
		r0 = rf(vote, recipientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
