// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	message "github.com/alvalor/consensus/message"
	mock "github.com/stretchr/testify/mock"
)

// ProposalCache is an autogenerated mock type for the ProposalCache type
type ProposalCache struct {
	mock.Mock
}

// Clear provides a mock function with given fields: height
func (_m *ProposalCache) Clear(height uint64) error {
	ret := _m.Called(height)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(height)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: proposal
func (_m *ProposalCache) Store(proposal *message.Proposal) (bool, error) {
	ret := _m.Called(proposal)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*message.Proposal) bool); ok {
		r0 = rf(proposal)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*message.Proposal) error); ok {
		r1 = rf(proposal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
