// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	message "github.com/alvalor/consensus/message"
	mock "github.com/stretchr/testify/mock"

	model "github.com/alvalor/consensus/model"
)

// Signer is an autogenerated mock type for the Signer type
type Signer struct {
	mock.Mock
}

// Proposal provides a mock function with given fields: block
func (_m *Signer) Proposal(block *model.Block) (*message.Proposal, error) {
	ret := _m.Called(block)

	var r0 *message.Proposal
	if rf, ok := ret.Get(0).(func(*model.Block) *message.Proposal); ok {
		r0 = rf(block)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*message.Proposal)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Block) error); ok {
		r1 = rf(block)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Vote provides a mock function with given fields: block
func (_m *Signer) Vote(block *model.Block) (*message.Vote, error) {
	ret := _m.Called(block)

	var r0 *message.Vote
	if rf, ok := ret.Get(0).(func(*model.Block) *message.Vote); ok {
		r0 = rf(block)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*message.Vote)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Block) error); ok {
		r1 = rf(block)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
