// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/alvalor/consensus/model"
	mock "github.com/stretchr/testify/mock"
)

// State is an autogenerated mock type for the State type
type State struct {
	mock.Mock
}

// Leader provides a mock function with given fields: height
func (_m *State) Leader(height uint64) model.Hash {
	ret := _m.Called(height)

	var r0 model.Hash
	if rf, ok := ret.Get(0).(func(uint64) model.Hash); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Hash)
		}
	}

	return r0
}

// Round provides a mock function with given fields:
func (_m *State) Round() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// Set provides a mock function with given fields: height
func (_m *State) Set(height uint64) {
	_m.Called(height)
}

// Threshold provides a mock function with given fields:
func (_m *State) Threshold() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}
