// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	message "github.com/alvalor/consensus/message"
	mock "github.com/stretchr/testify/mock"
)

// Verifier is an autogenerated mock type for the Verifier type
type Verifier struct {
	mock.Mock
}

// Proposal provides a mock function with given fields: proposal
func (_m *Verifier) Proposal(proposal *message.Proposal) (bool, error) {
	ret := _m.Called(proposal)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*message.Proposal) bool); ok {
		r0 = rf(proposal)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*message.Proposal) error); ok {
		r1 = rf(proposal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Vote provides a mock function with given fields: vote
func (_m *Verifier) Vote(vote *message.Vote) (bool, error) {
	ret := _m.Called(vote)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*message.Vote) bool); ok {
		r0 = rf(vote)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*message.Vote) error); ok {
		r1 = rf(vote)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
