// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import message "github.com/alvalor/consensus/message"
import mock "github.com/stretchr/testify/mock"
import model "github.com/alvalor/consensus/model"

// VoteCache is an autogenerated mock type for the VoteCache type
type VoteCache struct {
	mock.Mock
}

// Clear provides a mock function with given fields: height
func (_m *VoteCache) Clear(height uint64) error {
	ret := _m.Called(height)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(height)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Retrieve provides a mock function with given fields: height
func (_m *VoteCache) Retrieve(height uint64) (model.Hash, []*message.Vote, error) {
	ret := _m.Called(height)

	var r0 model.Hash
	if rf, ok := ret.Get(0).(func(uint64) model.Hash); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Hash)
		}
	}

	var r1 []*message.Vote
	if rf, ok := ret.Get(1).(func(uint64) []*message.Vote); ok {
		r1 = rf(height)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*message.Vote)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(uint64) error); ok {
		r2 = rf(height)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store provides a mock function with given fields: vote
func (_m *VoteCache) Store(vote *message.Vote) (bool, error) {
	ret := _m.Called(vote)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*message.Vote) bool); ok {
		r0 = rf(vote)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*message.Vote) error); ok {
		r1 = rf(vote)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
